# Generated by Django 5.2.8 on 2025-11-24 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Curso',
                'verbose_name_plural': 'Categorias de Cursos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_horas', models.PositiveIntegerField(help_text='Duracion total en horas')),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('cupo_maximo', models.PositiveIntegerField(default=50, help_text='Numero maximo de estudiantes')),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='ejemplos_para_cursos_online.categoriacurso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ('-fecha_creacion',),
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('secundaria', 'Secundaria'), ('tecnico', 'Tecnico'), ('universitario', 'Universitario'), ('postgrado', 'Postgrado'), ('profesional', 'Profesional')], max_length=20)),
                ('biografia', models.TextField(blank=True, help_text='Breve descripcion del estudiante')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField(blank=True, help_text='Contenido de la leccion')),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('texto', 'Texto'), ('pdf', 'PDF'), ('quiz', 'Quiz'), ('proyecto', 'Proyecto'), ('discusion', 'Discusion')], default='video', max_length=20)),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duracion estimada en minutos')),
                ('orden', models.PositiveIntegerField(help_text='Orden de la leccion en el curso')),
                ('es_gratuita', models.BooleanField(default=False, help_text='Si la leccion es de vista previa gratuita')),
                ('activa', models.BooleanField(default=True)),
                ('url_video', models.URLField(blank=True, help_text='URL del video si aplica')),
                ('url_archivo', models.URLField(blank=True, help_text='URL del archivo descargable si aplica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='ejemplos_para_cursos_online.curso')),
            ],
            options={
                'verbose_name': 'Leccion',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['curso', 'orden'],
                'unique_together': {('curso', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('quiz', 'Quiz'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('participacion', 'Participacion'), ('final', 'Evaluacion Final')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Calificacion obtenida', max_digits=5, null=True)),
                ('calificacion_maxima', models.DecimalField(decimal_places=2, default=100, help_text='Calificacion maxima posible', max_digits=5)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('comentarios_instructor', models.TextField(blank=True, help_text='Comentarios del instructor')),
                ('comentarios_estudiante', models.TextField(blank=True, help_text='Comentarios del estudiante')),
                ('archivo_entrega', models.URLField(blank=True, help_text='URL del archivo entregado por el estudiante')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='ejemplos_para_cursos_online.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='ejemplos_para_cursos_online.estudiante')),
                ('leccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='ejemplos_para_cursos_online.leccion')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagada', 'Pagada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('progreso', models.PositiveIntegerField(default=0, help_text='Porcentaje de progreso (0-100)')),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('notas_instructor', models.TextField(blank=True, help_text='Notas del instructor sobre el estudiante')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='ejemplos_para_cursos_online.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='ejemplos_para_cursos_online.estudiante')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
